### ISSUE TITLE
是用来解析独角兽的 combo url 吗？

### ISSUE THREAD

**Issue by meikidd** [yPangXie/koa-combo-parse#1]
如果是解析独角兽的 combo url 的话，要不要考虑一下跟 tianma-combo 模块的 parseURL 保持一致？
https://github.com/tianmajs/tianma-combo/blob/master/index.js

**Comment by yPangXie** [comment]
这个倒不是解析独角兽的url. 不过类似，目前是用来解析系统自己的静态文件～ 我去看看，参考一下～
